In [1]:
from scipy.optimize import linprog

# Coefficients of the objective function (maximize revenue)
c = [-5, -3]  # negative because linprog minimizes by default

# Coefficients of the inequality constraints (LHS)
A = [
    [2, 1],  # 2x + y <= 500
    [1, 1]   # x + y <= 400
]

# RHS of the inequality constraints
b = [500, 400]

# Coefficients of the lower bounds (demand constraints)
x_bounds = (100, None)  # x >= 100
y_bounds = (50, None)   # y >= 50

# Solve the linear programming problem
result = linprog(c, A_ub=A, b_ub=b, bounds=[x_bounds, y_bounds], method='highs')

# Output the result
print("Optimal number of chocolate cakes (x):", result.x[0])
print("Optimal number of vanilla cakes (y):", result.x[1])
print("Maximum revenue:", -result.fun)

Optimal number of chocolate cakes (x): 100.0
Optimal number of vanilla cakes (y): 300.0
Maximum revenue: 1400.0


In [2]:
def knapsack(weights, values, capacity):
    n = len(weights)  # number of items
    # Create a DP table with (n+1) rows and (capacity+1) columns
    dp = [[0] * (capacity + 1) for _ in range(n + 1)]

    # Build the DP table
    for i in range(1, n + 1):
        for w in range(1, capacity + 1):
            if weights[i - 1] <= w:  # if the item can be included
                # Max of not including or including the item
                dp[i][w] = max(dp[i - 1][w], dp[i - 1][w - weights[i - 1]] + values[i - 1])
            else:
                dp[i][w] = dp[i - 1][w]

    # The bottom-right cell contains the maximum value we can get
    return dp[n][capacity]

# Example usage
weights = [2, 3, 4, 5]  # Weights of the items
values = [3, 4, 5, 6]   # Values of the items
capacity = 5            # Capacity of the knapsack

max_value = knapsack(weights, values, capacity)
print(f"Maximum value that can be obtained: {max_value}")

Maximum value that can be obtained: 7


In [3]:
import numpy as np

def simplex(c, A, b):

    num_vars = len(c)
    num_constraints = len(b)

    tableau = np.zeros((num_constraints + 1, num_vars + num_constraints + 1))

    for i in range(num_constraints):
        tableau[i, :num_vars] = A[i]
        tableau[i, num_vars + i] = 1
        tableau[i, -1] = b[i]

    tableau[-1, :num_vars] = -c

    while np.any(tableau[-1, :-1] < 0):

        pivot_col = np.argmin(tableau[-1, :-1])

        ratios = tableau[:-1, -1] / tableau[:-1, pivot_col]
        ratios[ratios < 0] = np.inf
        pivot_row = np.argmin(ratios)

        pivot_value = tableau[pivot_row, pivot_col]
        tableau[pivot_row, :] /= pivot_value

        for i in range(num_constraints + 1):
            if i != pivot_row:
                tableau[i, :] -= tableau[i, pivot_col] * tableau[pivot_row, :]

    optimal_solution = tableau[:-1, -1]
    max_value = tableau[-1, -1]

    return optimal_solution, max_value

c = np.array([2, 3, 1])

A = np.array([
    [1, 1, 1],
    [1, 2, -1]
])

b = np.array([4, 2])

optimal_solution, max_value = simplex(c, A, b)

print("Optimal solution (u1, u2, u3):", optimal_solution)
print("Maximum profit:", max_value)

Optimal solution (u1, u2, u3): [2. 2.]
Maximum profit: 8.0


In [4]:
from scipy.optimize import linprog

# Coefficients of the objective function (profit)
c = [-200, -150]  # Negating to convert maximization to minimization

# Coefficients of the inequality constraints (Ax <= b)
A = [
    [1, 1],         # x + y <= 60 (Total land constraint)
    [20, 10],       # 20x + 10y <= 1200 (Fertilizer constraint)
    [10, 15],       # 10x + 15y <= 600 (Insecticide constraint)
]

# Right-hand side of the constraints
b = [60, 1200, 600]

# Bounds for x and y (Non-negativity and minimum acres constraints)
x_bounds = (20, None)  # At least 20 acres of wheat
y_bounds = (10, None)  # At least 10 acres of barley

# Solve the LP problem
result = linprog(c, A_ub=A, b_ub=b, bounds=[x_bounds, y_bounds], method='highs')

# Output the results
if result.success:
    x_opt = result.x[0]  # Optimal number of acres of wheat
    y_opt = result.x[1]  # Optimal number of acres of barley
    max_profit = -result.fun  # Convert back to the actual profit (negated in the objective)

    print(f"Optimal number of acres of wheat: {x_opt:.2f}")
    print(f"Optimal number of acres of barley: {y_opt:.2f}")
    print(f"Maximum profit: ${max_profit:.2f}")
else:
    print("No solution found.")

Optimal number of acres of wheat: 45.00
Optimal number of acres of barley: 10.00
Maximum profit: $10500.00


In [5]:
from scipy.optimize import linprog

# Coefficients of the objective function (profit)
c = [-20, -30]  # Negating to convert maximization to minimization

# Coefficients of the inequality constraints (Ax <= b)
A = [
    [1, 5],  # x + 5y <= 125 (Wood constraint)
    [3, 1],  # 3x + y <= 80 (Metal constraint)
]

# Right-hand side of the constraints
b = [125, 80]

# Bounds for x and y (non-negativity constraint)
x_bounds = (0, None)
y_bounds = (0, None)

# Solve the LP problem
result = linprog(c, A_ub=A, b_ub=b, bounds=[x_bounds, y_bounds], method='highs')

# Output the results
if result.success:
    x_opt = result.x[0]  # Optimal number of chairs
    y_opt = result.x[1]  # Optimal number of tables
    max_profit = -result.fun  # Convert back to the actual profit (negated in the objective)

    print(f"Optimal number of chairs: {int(x_opt)}")
    print(f"Optimal number of tables: {int(y_opt)}")
    print(f"Maximum profit: ${max_profit:.2f}")
else:
    print("No solution found.")

Optimal number of chairs: 19
Optimal number of tables: 21
Maximum profit: $1025.00


In [6]:
import numpy as np
from scipy.optimize import linear_sum_assignment

def hungarian_algorithm(cost_matrix):
    row_ind, col_ind = linear_sum_assignment(cost_matrix)

    total_cost = cost_matrix[row_ind, col_ind].sum()


    assignment = list(zip(row_ind, col_ind))

    return assignment, total_cost


cost_matrix = np.array([
    [9, 11, 14, 11, 7],
    [6, 15, 13, 13, 10],
    [12, 13, 6, 8, 8],
    [11, 9, 10, 12, 9],
    [7, 12, 14, 10, 14]
])

assignment, total_cost = hungarian_algorithm(cost_matrix)

print("Optimal Assignment (Task -> Worker):")
for task, worker in assignment:
    print(f"Task {task} -> Worker {worker}")

print(f"\nTotal Cost of Assignment: {total_cost}")

Optimal Assignment (Task -> Worker):
Task 0 -> Worker 4
Task 1 -> Worker 0
Task 2 -> Worker 2
Task 3 -> Worker 1
Task 4 -> Worker 3

Total Cost of Assignment: 38


In [7]:
import math

def EOQ(A,B,C):
    eoq=math.sqrt((2*A*B)/C)

    return eoq

a=float(input("Enter annual demand of the company:"))
b=float(input("Enter the ordering cost per order:"))
c=float(input("Enter the holding cost per year:"))

e=EOQ(a,b,c)
print("The Economic Order Quantity of the company:",e)

Enter annual demand of the company:1000
Enter the ordering cost per order:5
Enter the holding cost per year:2
The Economic Order Quantity of the company: 70.71067811865476


In [8]:
import math

def EOQ(A,B,C):
    eoq=math.sqrt((2*A*B)/C)

    return eoq

a=float(input("Enter annual demand:"))
b=float(input("Enter the ordering cost:"))
c=float(input("Enter the holding cost:"))

e=EOQ(a,b,c)
print("The Economic Order Quantity:",e)

Enter annual demand:1000
Enter the ordering cost:5
Enter the holding cost:2
The Economic Order Quantity: 70.71067811865476


In [9]:
import numpy as np

def vogel_approximation_method(supply, demand, costs):
    # Convert costs to float to handle np.inf assignments
    costs = costs.astype(float)
    transportation_plan = np.zeros_like(costs)
    total_cost = 0

    # Keep track of remaining supply and demand
    remaining_supply = supply.copy()
    remaining_demand = demand.copy()

    while np.sum(remaining_supply) > 0 and np.sum(remaining_demand) > 0:
        # Calculate row and column penalties
        row_penalties = []
        col_penalties = []

        # Calculate row penalties
        for i in range(costs.shape[0]):
            if remaining_supply[i] > 0:
                row_cost = costs[i, :]
                valid_cost = sorted([cost for cost in row_cost if cost != np.inf])
                if len(valid_cost) > 1:
                    row_penalties.append(valid_cost[1] - valid_cost[0])
                else:
                    row_penalties.append(0)
            else:
                row_penalties.append(-1)  # Mark as exhausted

        # Calculate column penalties
        for j in range(costs.shape[1]):
            if remaining_demand[j] > 0:
                col_cost = costs[:, j]
                valid_cost = sorted([cost for cost in col_cost if cost != np.inf])
                if len(valid_cost) > 1:
                    col_penalties.append(valid_cost[1] - valid_cost[0])
                else:
                    col_penalties.append(0)
            else:
                col_penalties.append(-1)  # Mark as exhausted

        # Determine whether to consider row or column penalty
        max_row_penalty = max([penalty for penalty in row_penalties if penalty >= 0], default=-1)
        max_col_penalty = max([penalty for penalty in col_penalties if penalty >= 0], default=-1)

        if max_row_penalty >= max_col_penalty:
            row_idx = row_penalties.index(max_row_penalty)
            col_idx = np.argmin(costs[row_idx, :])  # Choose the lowest cost in the row
        else:
            col_idx = col_penalties.index(max_col_penalty)
            row_idx = np.argmin(costs[:, col_idx])  # Choose the lowest cost in the column

        # Allocate the supply and demand
        allocated = min(remaining_supply[row_idx], remaining_demand[col_idx])
        transportation_plan[row_idx, col_idx] = allocated
        total_cost += allocated * costs[row_idx, col_idx]

        # Update supply and demand
        remaining_supply[row_idx] -= allocated
        remaining_demand[col_idx] -= allocated

        # Mark exhausted rows and columns as np.inf
        if remaining_supply[row_idx] == 0:
            costs[row_idx, :] = np.inf
        if remaining_demand[col_idx] == 0:
            costs[:, col_idx] = np.inf

    return transportation_plan, total_cost

# Example usage
supply = np.array([300, 400, 500])
demand = np.array([250, 350, 400, 200])
costs = np.array([
    [3, 1, 7, 4],
    [2, 6, 5, 9],
    [8, 3, 3, 2]
])

plan, cost = vogel_approximation_method(supply, demand, costs)
print("Optimal Transportation Plan:")
print(plan)
print("Total Transportation Cost:", cost)

Optimal Transportation Plan:
[[  0. 300.   0.   0.]
 [250.   0. 150.   0.]
 [  0.  50. 250. 200.]]
Total Transportation Cost: 2850.0


In [12]:
import sys
from itertools import permutations

def tsp():
    print("Enter the number of cities:")
    n = int(input())
    graph = {}
    cities = []

    print("Enter the city names (one per line):")
    for _ in range(n):
        city = input().strip()
        cities.append(city)
        graph[city] = {}

    print("Enter the distance matrix (row-wise, space-separated):")
    for i in range(n):
        distances = list(map(int, input().split()))
        for j in range(n):
            graph[cities[i]][cities[j]] = distances[j]

    print("Enter the starting city:")
    start = input().strip()

    nodes = list(graph.keys())
    nodes.remove(start)
    min_path = None
    min_cost = sys.maxsize

    for perm in permutations(nodes):
        current_cost = 0
        current_node = start
        for node in perm:
            current_cost += graph[current_node][node]
            current_node = node
        current_cost += graph[current_node][start]

        if current_cost < min_cost:
            min_cost = current_cost
            min_path = (start,) + perm + (start,)

    print("\nOptimal Path:", " -> ".join(min_path))
    print("Minimum Cost:", min_cost)

tsp()

Enter the number of cities:
3
Enter the city names (one per line):
a
b
c
Enter the distance matrix (row-wise, space-separated):
0 2 3
1 0 2
2 2 0
Enter the starting city:
a

Optimal Path: a -> b -> c -> a
Minimum Cost: 6
